<?php

return [
    'default_description' => 'Career Institute offers courses, certifications, testing services, career guidance, and flexible learning opportunities for students across Pakistan.',
    'default_image' => 'assets/images/img75.png',
    'descriptions' => [
        'home' => 'Elevate your skills and take your career to the next level with Career Institute, Pakistan\'s premier short courses provider. Master in-demand IT skills.',
        'about' => 'Learn about Career Institute, Pakistan\'s leading computer training institute, our mission, vision, professional courses, certifications, and student success.',
        'courses-certifications' => 'Explore professional computer courses and certifications at Career Institute. Build in-demand skills in IT, digital marketing, web development, design, and more',
        'course-detail' => 'Discover course details, practical learning outcomes, duration, and certification opportunities designed to help you build professional skills.',
        'category' => 'Browse Career Institute course categories and find practical learning paths in technology, design, business, language, and professional development.',
        'study-abroad' => 'Explore study abroad opportunities with Career Institute Pakistan. Get guidance on international education, admissions, scholarships, and planning your journey.',
        'stories' => 'Read inspiring student success stories from Career Institute. Discover real experiences, achievements, and career journeys shaped by professional education.',
        'events' => 'Explore upcoming Career Institute workshops, career fairs, training sessions, and campus events designed to connect learners with new opportunities.',
        'events.show' => 'View complete event details, including date, venue, registration information, and practical opportunities available through Career Institute.',
        'news' => 'Stay informed with the latest Career Institute news, announcements, student achievements, industry updates, and opportunities for professional growth.',
        'news-detail' => 'Read Career Institute news, announcements, achievements, and industry updates that help students make informed decisions about their future careers.',
        'blogs' => 'Explore practical articles, career advice, technology insights, and learning resources from Career Institute to support your professional growth.',
        'blog-detail' => 'Read practical Career Institute insights, career advice, and learning resources that help students develop in-demand, real-world professional skills.',
        'faqs' => 'Find answers to common questions about Career Institute courses, admissions, certifications, learning options, campus facilities, and career guidance.',
        'contact-us' => 'Contact Career Institute for course details, admissions, certifications, exams, and support. Get in touch with our team and take the next step in your career.',
        'ambassador-program' => 'Join the Career Institute Ambassador Program and help students discover career-focused courses while gaining recognition, networking, and valuable opportunities.',
        'coworking-space' => 'Find a professional coworking space in Pakistan at Career Institute. Enjoy a productive workspace, essential facilities, and a professional environment.',
        'gallery' => 'Explore Career Institute campus life, workshops, student activities, events, and learning spaces through our latest photos and visual highlights.',
        'how-to-pay' => 'Learn how to pay your Career Institute course fees through convenient payment methods. Follow our simple payment guide for a smooth enrollment process.',
        'kryterion' => 'Schedule your Kryterion exam at Career Institute in Pakistan. Enjoy a professional testing environment and reliable exam support for your certification journey.',
        'pearson-vue' => 'Book your Pearson VUE exam at Career Institute, an authorized testing center in Pakistan. Get a secure, professional environment for your certification exam.',
        'psi-exam' => 'Take your PSI exams at Career Institute in Pakistan. Access a professional testing environment and complete your certification exams with confidence and ease.',
        'verifications' => 'Verify your Career Institute certificate online with our verification service. Confirm certificate authenticity quickly and easily using your details.',
        'job-placement' => 'Discover job placement services at Career Institute Pakistan. Get career guidance, employment support, and opportunities to connect your skills with employers.',
        'privacy-policy' => 'Review Career Institute privacy practices and understand how we collect, use, protect, and manage personal information across services for visitors.',
    ],
];
